inherit_from: ./config/default_edge.yml

inherit_gem:
  rubocop-rootstrap:
    - config/rails_edge.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/bundle/**/*

Lint/MissingSuper:
  Exclude:
    - app/services/*